version: '3'
services:
  active-user-processing:
    image: "active-user-processing"
    build: ./ActiveUserProcessingService
    ports:
      - "8081:8081"
  active-user:
    image: "active-user"
    build: ./ActiveUser
    ports:
      - "8082:8082"
  redis:
    image: "redis:alpine"
